[package]
name = "my_lib"
version = "0.3.0"
authors = ["DrFlowerkick <flowerkick14@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"